# Generated by Django 5.2.4 on 2025-07-16 16:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления в систему')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления в системе')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('contact_data', models.CharField(max_length=255, verbose_name='Контактные данные')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления в систему')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления в системе')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('experience', models.IntegerField(default=0, verbose_name='Стаж')),
                ('anthropometric', models.JSONField(blank=True, null=True, verbose_name='Антропометрические данные')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления в систему')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления в системе')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат')),
                ('coaches', models.ManyToManyField(related_name='games', to='api.coach', verbose_name='Тренеры')),
                ('players', models.ManyToManyField(related_name='games', to='api.player', verbose_name='Игроки')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления в систему')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления в системе')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(help_text='В секундах от начала игры', verbose_name='Временная метка (секунда)')),
                ('x_coordinate', models.FloatField(blank=True, null=True, verbose_name='Координата X')),
                ('y_coordinate', models.FloatField(blank=True, null=True, verbose_name='Координата Y')),
                ('z_coordinate', models.FloatField(blank=True, null=True, verbose_name='Координата Z')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='Скорость')),
                ('additional_parameters', models.JSONField(blank=True, null=True, verbose_name='Дополнительные параметры')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_positions', to='api.game', verbose_name='Игра')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_positions', to='api.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Позиция игрока',
                'verbose_name_plural': 'Позиции игроков',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления в систему')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления в системе')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
                ('city_region', models.CharField(max_length=255, verbose_name='Город/Регион')),
                ('coaches', models.ManyToManyField(related_name='teams', to='api.coach', verbose_name='Тренеры')),
                ('players', models.ManyToManyField(related_name='teams', to='api.player', verbose_name='Игроки')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(related_name='games', to='api.team', verbose_name='Команды-участники'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('datetime__lte', datetime.datetime(2025, 7, 16, 16, 56, 12, 595651, tzinfo=datetime.timezone.utc))), name='game_date_past'),
        ),
    ]
