# Generated by Django 5.2.4 on 2025-07-17 11:21

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name='game_date_past',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_team', to='api.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='player',
            name='experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Стаж'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('datetime__lte', datetime.datetime(2025, 7, 17, 11, 21, 14, 789590, tzinfo=datetime.timezone.utc))), name='game_date_past'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('experience__gte', 0), ('experience__lte', 100)), name='experience_range'),
        ),
    ]
