# Generated by Django 5.2.4 on 2025-07-17 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_game_game_date_past_player_team_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name='game_date_past',
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('datetime__lte', datetime.datetime(2025, 7, 17, 11, 30, 23, 946882, tzinfo=datetime.timezone.utc))), name='game_date_past'),
        ),
    ]
