# Generated by Django 5.2.4 on 2025-07-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_game_game_date_past_game_game_date_past'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name='game_date_past',
        ),
        migrations.RenameField(
            model_name='playerposition',
            old_name='games',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='playerposition',
            old_name='players',
            new_name='player',
        ),
    ]
