# Generated by Django 5.2.4 on 2025-07-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_game_game_date_past_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
    ]
